### ISSUE TITLE
Menu interfers with iPhone X swipebar

### ISSUE THREAD

**Issue by cedricaebi** [vaadin/vaadin-app-layout#72] opened 2019-03-20 15:20 UTC
When installed as a PWA the menu-items are lying below the iPhone X swipebar, and therefore the menu cant be scrolled horizontally

**Comment by oluwasayo** [comment] 2019-06-10 15:28
Not reproducible on master. It means this ticket should be resolved on next release.

**Comment by web-padawan** [comment] 2020-02-13 17:19
I tried `vaadin-app-layout` on iPhone X recently and could not reproduce this either.

Closing as invalid. If this is still a problem, please submit a new issue, preferably with a screenshot.

**Closed by web-padawan** 2020-02-13 17:19 UTC
