### ISSUE TITLE
[3.0.0-alpha1] Lumo/Material Theme styles can be loaded after custom styles

### ISSUE THREAD

**Issue by moderndeveloperllc** [vaadin/vaadin-app-layout#144] opened 2020-02-18 22:09 UTC
When using `registerStyles()` to add custom styles, they can be loaded _before_ the Lumo/Material Theme styles. This is because the custom styles need to be loaded before `vaadin-app-layout` is loaded so the styles aren't finalized. As the Lumo/Material Theme styles have no module ID, they are created as `custom-style-module-xxx` (https://github.com/vaadin/vaadin-themable-mixin/blob/master/register-styles.html#L26) the same as other custom styles. Being loaded later than those custom styles can lead to them being numbered higher (when using a packager like webpack for instance).

This can be mitigated by adding a `moduleId` that indicates it's Vaadin theme CSS:
```
registerStyles('vaadin-app-layout', appLayoutStyles, {moduleId:'lumo-app-layout'});
```
`registerStyles()` will sort these first - before any custom styles (https://github.com/vaadin/component-mixins/blob/master/packages/themable-element/themable-element.ts#L10)

Some of the docs indicate that moduleId is deprecated. If so, another way to get those Vaadin Theme files loaded first is needed.

**Comment by web-padawan** [comment] 2020-02-19 07:32
Thanks for reporting. Actually this issue affects all the components using LitElement.

We will have to use `moduleId` for now, to get rid of this regression.

**Comment by web-padawan** [comment] 2020-02-24 11:33
Fixed by d12bfe1. Also fixed for details, accordion and tabs components.
We are going to release new alphas as soon as `lit-element` 2.3.0 is out.

**Closed by web-padawan** 2020-02-24 11:33 UTC
Labels: next

**Comment by moderndeveloperllc** [comment] 2020-02-24 14:32
@web-padawan Waiting for https://github.com/Polymer/lit-element/pull/866 to be released? Sounds good. Hopefully they will get 2.3.0 out at some point soon! Does https://github.com/vaadin/component-mixins/issues/53 seem like a good way forward?

**Comment by web-padawan** [comment] 2020-02-24 16:15
Yes, we need a LitElement release because of that `getStyles` API.

Not sure if we are going to implement ordering for `registerStyles` at the moment.

**Comment by moderndeveloperllc** [comment] 2020-03-18 21:02
@web-padawan FYI, 2.3.0 is getting released right now.

**Comment by web-padawan** [comment] 2020-03-18 21:14
Thanks, I'm in progress of updating components. We will do the actual releases tomorrow.
